### ISSUE TITLE
As discussed

### ISSUE THREAD

**Issue by pillepalle1** [buka-gaming/viewer#1]
啤酒男爵:
Kannst du den bring-in bitte hardcoden bis die Interaktion mit der Datenbank vollstaendig implementiert ist?

啤酒男爵:
Bspw wurde der Sit-In nicht ausgefuehrt, weil der Stack 0 war 

🦄:
Ich reagiere nur auf GitHub issues

**Comment by buhrmi** [comment]
i don't know what "den bring-in bitte hardcoden" means

**Comment by buhrmi** [comment]
ah, do you mean hardcoding an amount? eg always send 100 no matter the player's balance?
